# Generated by Django 6.0 on 2025-12-26 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0002_alter_offer_user_alter_offerdetail_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='features',
        ),
        migrations.CreateModel(
            name='OfferDetailFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('offer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='freelance_app.offerdetail')),
            ],
        ),
    ]
