# Generated by Django 6.0 on 2025-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance_app', '0003_remove_offerdetail_features_offerdetailfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='OfferDetailFeature',
        ),
    ]
