# Generated by Django 6.0 on 2025-12-22 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
                ('location', models.CharField(blank=True, max_length=20)),
                ('telephone_number', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('working_hours', models.CharField(blank=True, max_length=10)),
                ('user_type', models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
