# Generated by Django 6.0 on 2026-01-13 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('location', models.CharField(blank=True, max_length=20)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('working_hours', models.CharField(blank=True, max_length=1000)),
                ('type', models.CharField(choices=[('customer', 'customer'), ('business', 'business')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
