# Generated by Django 6.0 on 2025-12-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_userprofile_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='telephone_number',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_type',
            new_name='type',
        ),
    ]
