# Generated by Django 6.0 on 2025-12-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_telephone_number_userprofile_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file',
            field=models.FileField(blank=True, upload_to='profiles/'),
        ),
    ]
